-- 코드를 입력하세요
SELECT c.AUTHOR_ID, d.AUTHOR_NAME, c.CATEGORY, SUM(c.TEMP) as TOTAL_SALES
FROM (
    SELECT b.BOOK_ID, b.AUTHOR_ID, sum(SALES) * b.PRICE as TEMP, b.CATEGORY
    FROM BOOK_SALES as a
    LEFT JOIN BOOK as b
    ON a.BOOK_ID = b.BOOK_ID
    WHERE a.SALES_DATE BETWEEN '2022-01-01' and '2022-01-31'
    GROUP BY a.BOOK_ID
) as c
LEFT JOIN AUTHOR as d
ON c.AUTHOR_ID = d.AUTHOR_ID
GROUP BY c.AUTHOR_ID, c.CATEGORY
ORDER BY c.AUTHOR_ID, c.CATEGORY desc;
