-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * ((100 - B.DISCOUNT_RATE) / 100) * 30) as FEE
FROM CAR_RENTAL_COMPANY_CAR as A
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as B
ON A.CAR_TYPE = B.CAR_TYPE AND B.DURATION_TYPE = '30일 이상'
WHERE A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND
    START_DATE < '2022-12-01'
) AND A.CAR_TYPE IN ('세단', 'SUV') AND
ROUND(A.DAILY_FEE * ((100 - B.DISCOUNT_RATE) / 100) * 30) BETWEEN 500000 AND 1999999
ORDER BY FEE desc, A.CAR_TYPE, A.CAR_ID desc;