-- 코드를 입력하세요
SELECT a.REST_ID, b.REST_NAME, b.FOOD_TYPE, b.FAVORITES, b.ADDRESS,
ROUND(AVG(a.REVIEW_SCORE), 2) as SCORE
FROM REST_REVIEW as a
LEFT JOIN REST_INFO as b
ON a.REST_ID = b.REST_ID
WHERE b.ADDRESS like '서울%'
GROUP BY a.REST_ID
ORDER BY SCORE desc, b.FAVORITES desc;
# SELECT *
# FROM REST_REVIEW as a
# LEFT JOIN REST_INFO as b
# ON a.REST_ID = b.REST_ID