-- 코드를 입력하세요
SELECT YEAR(a.SALES_DATE) as YEAR, MONTH(a.SALES_DATE) as MONTH, b.GENDER, count(DISTINCT b.USER_ID) as USERS
FROM ONLINE_SALE as a
LEFT JOIN USER_INFO as b
ON a.USER_ID = b.USER_ID
WHERE b.GENDER IS NOT NULL
GROUP BY YEAR(a.SALES_DATE), MONTH(a.SALES_DATE), b.GENDER
ORDER BY YEAR, MONTH, GENDER;