-- 코드를 입력하세요
SELECT A.HISTORY_ID, 
CASE 
WHEN C.DISCOUNT_RATE IS NOT NULL THEN ROUND(A.DATE * (B.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100)) ELSE B.DAILY_FEE * A.DATE END AS FEE
FROM (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 as DATE, CASE 
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 then '90일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 then '30일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 then '7일 이상'
    end AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) as A 
LEFT JOIN
CAR_RENTAL_COMPANY_CAR as B
ON A.CAR_ID = B.CAR_ID LEFT JOIN
CAR_RENTAL_COMPANY_DISCOUNT_PLAN as C
ON C.CAR_TYPE = B.CAR_TYPE AND A.DURATION_TYPE = C.DURATION_TYPE
WHERE B.CAR_TYPE = '트럭'
ORDER BY FEE desc, A.HISTORY_ID desc
