-- 코드를 입력하세요
SELECT a.APNT_NO, c.PT_NAME, a.PT_NO, a.MCDP_CD, b.DR_NAME, a.APNT_YMD
FROM APPOINTMENT as a
LEFT JOIN DOCTOR as b
ON a.MDDR_ID = b.DR_ID
LEFT JOIN PATIENT as c
ON a.PT_NO = c.PT_NO
WHERE a.APNT_YMD like '2022-04-13%' and
a.APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD;