# -- 코드를 입력하세요
SELECT b.MEMBER_NAME, a.REVIEW_TEXT, DATE_FORMAT(a.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW as a
LEFT JOIN MEMBER_PROFILE as b
ON a.MEMBER_ID = b.MEMBER_ID
WHERE a.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) desc
    LIMIT 1
)
ORDER BY a.REVIEW_DATE, a.REVIEW_TEXT;