-- 코드를 입력하세요
SELECT MONTH(START_DATE) as MONTH, CAR_ID, count(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') BETWEEN '2022-08-01' and '2022-10-31' AND
CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') BETWEEN '2022-08-01' and '2022-10-31'
    GROUP BY CAR_ID
    HAVING count(*) >= 5
)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID desc;