-- 코드를 입력하세요
SELECT DISTINCT(a.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR as a
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as b
ON a.CAR_ID = b.CAR_ID
WHERE a.CAR_TYPE = '세단' and b.START_DATE like '2022-10%'
ORDER BY a.CAR_ID desc;